### ISSUE TITLE
Install MikTeX

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-appveyor#10]
See http://docs.miktex.org/manual/setupwiz.html, especially the `--unattended` switch.

**Comment by krlmlr** [comment]
Not dealing with vignettes and manuals for now.

**Comment by pat-s** [comment]
@krlmlr 
A working solution adapted from https://help.appveyor.com/discussions/suggestions/353-install-miktex-latex#comment_41113616

```yml
 # Install miktex to get pdflatex, if we don't get it from the cache
 - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe appveyor DownloadFile https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable-2.9.6753.exe
 - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe 7z x miktex-portable-2.9.6753.exe -oC:\miktex >NUL
 - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin"
 # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
 # this adds this to the registry!
 - initexmf --set-config-value "[MPM]AutoInstall=1"
```

Build log: https://ci.appveyor.com/project/pat-s/mlr3-xml46/build/1.0.13#L14962

Add to README?

**Comment by krlmlr** [comment]
This, or _tinytex_. The code should probably live in the PowerShell script and be triggered by an environment variable; this then should be part of the README.

**Comment by krlmlr** [comment]
Added docs in 6d4e10b.
