### ISSUE TITLE
Rtools not available for upstream dependencies

### ISSUE THREAD

**Issue by wch** [krlmlr/r-appveyor#104]
In this [build of shiny](https://ci.appveyor.com/project/rstudio/shiny/build/1.0.1685#L42), it fails because Rtools is not installed, but that version of Shiny has some dependencies (later and httpuv) that it's getting from GitHub and require a compiler.

I see in #41 that there is a workaround, but it seems clunky. I have a feeling that this scenario is not uncommon when the `Remotes:` field is used in a DESCRIPTION file.

Would it be possible to add something to a repo's appveyor.yml file that tells it to install Rtools?

**Comment by gaborcsardi** [comment]
Maybe I am missing something, but can you add `USE_RTOOLS`? Example:
https://github.com/r-lib/callr/blob/f68b62e46be75ed7a6040555f0e7bd028951d3d3/appveyor.yml#L49

**Comment by wch** [comment]
@gaborcsardi Setting `USE_RTOOLS` works. Thanks!
