### ISSUE TITLE
Link against external libraries

### ISSUE THREAD

**Issue by Marlin-Na** [krlmlr/r-appveyor#105]
In the win-builder of CRAN, it says that there are [Make variables pointing to the corresponding libraries](https://cran.r-project.org/bin/windows/contrib/ThirdPartySoftware.html). Is it possible to use them in appveyor? More specifically, I would like to link against `gmp` and `mpfr` libraries. I tried to use `$(LIB_MPFR)` and `$(LIB_GMP)` in `Makevars.win` but it does not seem to work.

**Comment by krlmlr** [comment]
Currently you need to download/install the libraries yourself, and also set the corresponding environment variables. Maybe you can borrow from other projects?

**Comment by Marlin-Na** [comment]
Thanks for the answer! I will try that approach.

**Comment by Marlin-Na** [comment]
Hi @krlmlr , I am not sure how to set Make variables for use of `Makevars`, can you point me out any specific example `appveyor.yml` file?
Thanks a lot!

**Comment by krlmlr** [comment]
Make will pick up regular environment variables which you can define in the `environment` section of `appveyor.yml`: https://github.com/krlmlr/r-appveyor/blob/a92cb8434c042d9232314ecd9c78161fc605b279/appveyor.yml#L16.

**Comment by Marlin-Na** [comment]
@krlmlr Thanks a lot! It is clear for me now.
