### ISSUE TITLE
testthat::skip_on_cran() also skips on appveyor 

### ISSUE THREAD

**Issue by hughjonesd** [krlmlr/r-appveyor#108]
(But not e.g. Travis, I think.)

This could be avoided by setting the NOT_CRAN environment variable, which the function tests for.

**Comment by hughjonesd** [comment]
Heh, or I could do it myself:
```
environment:
  NOT_CRAN: true
```

Perhaps this could be in the documentation or added to the default from devtools.

**Comment by krlmlr** [comment]
Happy to have this in the README. Would you like to submit a PR?

**Comment by krlmlr** [comment]
Closed in 6bef152.
