### ISSUE TITLE
USE_RTOOLS implicitly set to true if required?

### ISSUE THREAD

**Issue by wibeasley** [krlmlr/r-appveyor#111]
In the same way that `USE_RTOOLS` is essentially set to true [if there's a src/ directory](https://github.com/krlmlr/r-appveyor/blob/a92cb8434c042d9232314ecd9c78161fc605b279/scripts/appveyor-tool.ps1#L161), would it make sense to automatically install Rtools if the AppVeyor script tried to run `- travis-tool.sh install_github qqq/mmm`?

If not, is there a benefit in throwing a warning along the lines of this?
> Warning, r-appveyor is attempting to install a package from source, without first installing Rtools.  Consider setting `USE_RTOOLS=true` in appveyor.yml after consulting the documentation at https://github.com/krlmlr/r-appveyor/.

The existing documentation is very clear, but I still overlooked it tonight, and it appears that a few other people have made the same oversight:
* https://github.com/krlmlr/r-appveyor/issues/104#issuecomment-366264047
* https://github.com/krlmlr/r-appveyor/issues/69
* https://github.com/krlmlr/r-appveyor/issues/77

**Comment by hughjonesd** [comment]
Me too on this. I could try for a PR?

**Comment by krlmlr** [comment]
Do we always need Rtools when installing from GitHub?

@jimhester: Would you consider an "install Rtools if needed" option for `pkginstall::install_*()`? AppVeyor would be its only legitimate user, though...

**Comment by jimhester** [comment]
You only need Rtools if the dependencies you are installing need compiled code

Using pkgdepends we will be able to tell before installation if any of your dependencies need compiled code, because it resolves all dependencies prior to beginning installation. So once that is working it should not be hard to have appveyor automatically install Rtools if needed.

**Comment by krlmlr** [comment]
Closing for now, we have `PKGTYPE=win.binary` by default which should resolve most of the pain points.
