### ISSUE TITLE
build failing with "Warning: dependency 'data.table' is not available"

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#117]
I have been facing an issue with getting my AppVeyor build to succeed and I am not sure what to do, so I am raising this issue here. I have two packages, both of which are succeeding with `TravisCI` builds, but failing on `AppVeyor` for a common reason-

For ggstatsplot (https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/build/artifacts)
```
* installing *source* package 'ggstatsplot' ...
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'data.table'
ERROR: lazy loading failed for package 'ggstatsplot'
* removing 'C:/projects/ggstatsplot/ggstatsplot.Rcheck/ggstatsplot'
In R CMD INSTALL
```
The same error is also observed for my other package `groupedstats` (https://ci.appveyor.com/project/IndrajeetPatil/groupedstats/build/artifacts).

I am not sure why I'm getting this error because `data.table` is clearly there on CRAN and seems to be working with the current version of R (https://cran.r-project.org/web/checks/check_results_data.table.html). 

Any thoughts on what's going on?

**Comment by rorynolan** [comment]
I'm getting a similar error at https://ci.appveyor.com/project/rorynolan/exampletestr. On line 200, I have
```
Skipping 1 packages not available: desc
```
which eventually causes the check to fail.

**Comment by IndrajeetPatil** [comment]
@rorynolan Turns out the error I am getting has nothing to do with `AppVeyor`: https://github.com/Rdatatable/data.table/issues/2794#issuecomment-383958639

I think similar issue exists for `desc` with the new release of R (3.5):
https://cran.r-project.org/web/checks/check_results_desc.html

**Comment by rorynolan** [comment]
Thanks a lot for addressing my comment too @IndrajeetPatil :-)

**Comment by krlmlr** [comment]
Should work better now with the new default `PKGTYPE=win.binary`. Please open a new issue if necessary.
