### ISSUE TITLE
32-bit Rtools on 64-bit build?

### ISSUE THREAD

**Issue by thk686** [krlmlr/r-appveyor#118]
The output below suggests that the 32-bit version of nm is being called on 64-bit ouput.

C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o kdtools.dll tmp.def RcppExports.o arrayvec.o kdtools.o -Lc:/R/bin/x64 -lR
C:\Rtools\mingw_32\bin\nm.exe: C:/projects/kdtools/kdtools.Rcheck/00_pkg_src/kdtools/src-x64/RcppExports.o: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: C:/projects/kdtools/kdtools.Rcheck/00_pkg_src/kdtools/src-x64/arrayvec.o: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: C:/projects/kdtools/kdtools.Rcheck/00_pkg_src/kdtools/src-x64/kdtools.o: File format not recognized
Warning messages:
1: In system(sprintf("%s -Pg %s", shQuote(nm), shQuote(f)), intern = TRUE) :
  running command '"C:\Rtools\mingw_32\bin\nm.exe" -Pg "C:/projects/kdtools/kdtools.Rcheck/00_pkg_src/kdtools/src-x64/RcppExports.o"' had status 1
2: In system(sprintf("%s -Pg %s", shQuote(nm), shQuote(f)), intern = TRUE) :
  running command '"C:\Rtools\mingw_32\bin\nm.exe" -Pg "C:/projects/kdtools/kdtools.Rcheck/00_pkg_src/kdtools/src-x64/arrayvec.o"' had status 1
3: In system(sprintf("%s -Pg %s", shQuote(nm), shQuote(f)), intern = TRUE) :
  running command '"C:\Rtools\mingw_32\bin\nm.exe" -Pg "C:/projects/kdtools/kdtools.Rcheck/00_pkg_src/kdtools/src-x64/kdtools.o"' had status 1
installing to C:/projects/kdtools/kdtools.Rcheck/kdtools/libs/x64

**Comment by krlmlr** [comment]
Thanks. We changed the default to be 64 bits recently, is this still a problem?
