### ISSUE TITLE
Rtools installation hangs

### ISSUE THREAD

**Issue by LiNk-NY** [krlmlr/r-appveyor#120]
Hi Kirill, @krlmlr 

I'm trying to test a CRAN package on multiple Windows architectures. 
Please see: https://ci.appveyor.com/project/Bioconductor/biocmanager

All builds seem to hang at the Rtools installation: 

```
    Directory: C:\
Mode                LastWriteTime         Length Name                                                                                                                                                                                
----                -------------         ------ ----                                                                                                                                                                                
d-----         6/4/2018  11:11 PM                RLibrary                                                                                                                                                                            
== 06/04/2018 23:11:47: Setting TAR to 'internal'
== 06/04/2018 23:11:47: Bootstrap: Done
== 06/04/2018 23:11:47: Determining Rtools version
== 06/04/2018 23:11:47: Downloading Rtools from: https://cloud.r-project.org/bin/windows/Rtools/Rtools35.exe
== 06/04/2018 23:11:53: Running Rtools installer
```

I don't think there's an issue with the `yaml` file:
https://github.com/Bioconductor/BiocManager/blob/master/appveyor.yml

Am I missing something here? 

Thanks for your help. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi Kirill, @krlmlr 
Any updates / suggestions on this? Thanks a bunch!

**Comment by krlmlr** [comment]
This is very strange, _dplyr_ tests can install Rtools: https://ci.appveyor.com/project/tidyverse/dplyr/build/job/b2e9yglij341adni#L41.

You could try establishing an RDP connection to the AppVeyor builder and see what's happening: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/.

**Comment by averissimo** [comment]
I'm having the same problem, did you solve it?

https://ci.appveyor.com/project/averissimo/loose-rock/build/1.0.5

**Comment by LiNk-NY** [comment]
I didn't solve it. I avoided the issue by not installing RTools, i.e., removing the `InstallRtools` line in the `appveyor.yml`:
```
install:
  ps: |
        Bootstrap
        InstallRtools
```

**Comment by averissimo** [comment]
Brilliant!! Now I can test my packages in windows environment :)
