### ISSUE TITLE
Won't install R when all of my R code is in a subfolder.

### ISSUE THREAD

**Issue by Fazendaaa** [krlmlr/r-appveyor#123]
I'm getting the following error from AppVeyor build console:

> 'travis-tool.sh' is not recognized as an internal or external command,
operable program or batch file.

But I think this might be some issue related to changing directories. I've tried to change this "cd" script from before_build to before_test, still not working. This is the output: https://ci.appveyor.com/project/Fazendaaa/project-euler/build/1.0.14

**Comment by krlmlr** [comment]
There should be a `travis-tool.sh.cmd` on your `PATH` after the `Bootstrap` section. Maybe you could try debugging your build with https://www.appveyor.com/docs/how-to/rdp-to-build-worker/?

**Comment by Fazendaaa** [comment]
In the end, I've decided to not approach like this and I've ended up building a Docker image to run it: https://github.com/Fazendaaa/project-euler/blob/master/appveyor.yml

Thank you, @krlmlr for all of your support :)
