### ISSUE TITLE
Bioconductor integration

### ISSUE THREAD

**Issue by LiNk-NY** [krlmlr/r-appveyor#126]
Hi all,
I'm opening this issue as requested by @krlmlr. 
There are a few issues related to integrating Bioconductor already open. 
See: #125, #65, ~ #57 

### Support for BiocManager

Bioconductor has recently switched to using `BiocManager` [CRAN package](https://CRAN.r-project.org/package=BiocManager) to install and update Bioconductor packages. This makes it
a bit easier to support via CI services by just adding `BiocManager` to the list of CRAN packages.

I've created a PR #125 to support this: 
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
```

Unfortunately, this method only works with R versions `>= 3.5.0`. Support for packages
wishing to test against older versions of R is still needed.

### Support for BiocCheck

This could be implemented as a field in the the `appveyor.yml` file for running `BiocCheck`
on a Bioconductor package such as `- travis-tool.sh bioc_check`.
I'm willing to look into this and provide some guidance / PR. 
_Note_. This has been implemented in the Travis CI builds. 

### Using `BiocManager::repositories`

Support installations from Bioconductor repositories by using `BiocManager::repositories`.
It will potentially avoid issues such as #57.

**Comment by mjsteinbaugh** [comment]
I'm up for helping fix r-appveyor and getting Bioconductor 3.8 deployed as the default

**Comment by LiNk-NY** [comment]
Hi Michael, @mjsteinbaugh 
I think the PR should be enough to get it working with Bioconductor 3.8. 
It would be good to address the other objectives here such as supporting
the use of `BiocCheck` as part of the testing process. 

-MR

**Comment by krlmlr** [comment]
The PR is merged, closing. Please open a new issue if necessary.
