### ISSUE TITLE
Reports "Error: (converted from warning)"... appears to be ignoring some environment settings in appveyor.yml

### ISSUE THREAD

**Issue by pcarbo** [krlmlr/r-appveyor#127]
It appears that something changed with Appveyor in the past week, because the Appveyor tests for my R packages tests were working fine up until a few days ago. It now appears to be ignoring some of the configuration in the YAML file. Do you have any idea what might be going on with Appveyor? 

In my YAML file, I have (among other settings):

```yaml
environment:
  global:
    _R_CHECK_FORCE_SUGGESTS_: false
    WARNINGS_ARE_ERRORS:
```

and yet Appveyor still reports (for the suggested packages):

```
Skipping 3 packages not available: ExtremeDeconvolution, flashr, mixsqp
...
Error: (converted from warning) packages 'ExtremeDeconvolution', 'flashr', 'mixsqp' are not available (for R version 3.5.1)
Execution halted
Command exited with code 1
```

The error only occured after I forced a re-build (no new commits).

See [here](https://ci.appveyor.com/project/pcarbo/mashr) for a full example of this. Any help or insight would be much appreciated! And I'm happy to provide more details to help isolate the issue.

**Comment by gaborcsardi** [comment]
See https://github.com/krlmlr/r-appveyor/issues/57#issuecomment-429301363

**Comment by pcarbo** [comment]
@gaborcsardi Seems to be working! I don't quite fully understand what the issue was, but thanks! Maybe `R_REMOTES_NO_ERRORS_FROM_WARNINGS` should be mentioned somewhere in the README? I think others could benefit.

**Comment by pcarbo** [comment]
Regardless, feel free to close the issue as you see fit.
