### ISSUE TITLE
Build fails when compiling Rcpp 1.0.0

### ISSUE THREAD

**Issue by tylerlittlefield** [krlmlr/r-appveyor#130]
[**Here**](https://ci.appveyor.com/project/tyluRp/treeco/builds/20124128) is the last one to pass. After this, the following [**build**](https://ci.appveyor.com/project/tyluRp/treeco/builds/20155730) fails and continues to do so at the same spot every time. Any thoughts?

**Comment by gaborcsardi** [comment]
You don't have a C compiler. Please either:
- set `USE_RTOOLS`, see the README, or several closed issues here, this will install a C compiler, or
- set `R_COMPILE_AND_INSTALL_PACKAGES=never`, that will force using the latest binary build of Rcpp.
