### ISSUE TITLE
mix up in the package installation order in the presence of source packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#134]
My package depends on both `tibble` and `sjstats`, both of which had a new release on `CRAN`. So once I bumped up versions for these dependencies, my `Appveyor` builds rely on `source` versions of these packages.

![image](https://user-images.githubusercontent.com/11330453/50810243-94f4b800-132e-11e9-969d-2cf19c31c54b.png)

But the builds are [failing](https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/builds/21453200) with the following error-
```r
* installing *source* package 'sjstats' ...
** package 'sjstats' successfully unpacked and MD5 sums checked
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'tibble'
ERROR: lazy loading failed for package 'sjstats'
* removing 'c:/RLibrary/sjstats'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package 'sjstats' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
```

Does this have something to do with the order in which `source` versions of packages are being downloaded? `sjstats` is attempted to download before `tibble` and since `sjstats` relies on `tibble`, it fails? 

If that's the case, is this a bug? Should `Appveyor` figure out the dependency structure within the source versions of packages?

**Comment by krlmlr** [comment]
Thanks. This problem should be gone as soon as the binary versions of _tibble_ 2.0.0 are on CRAN, any moment now.

@gaborcsardi: `remotes::install_deps()` seems to mix up the package installation order in the presence of source packages on Windows. Any idea?

https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/builds/21453200#L2077

**Comment by gaborcsardi** [comment]
Please report an issue. Thanks.

**Comment by IndrajeetPatil** [comment]
Here is another example of this-
https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/build/job/v33rv5dn3ti97aly

Source versions:
![image](https://user-images.githubusercontent.com/11330453/53059622-7df4ca00-3485-11e9-92a9-c639f700b27f.png)

But since `afex` needs `haven` upstream, it fails since `haven` hasn't been installed yet-
![image](https://user-images.githubusercontent.com/11330453/53059673-b399b300-3485-11e9-917d-035d2b29c59b.png)
