### ISSUE TITLE
Build failing due to curl update

### ISSUE THREAD

**Issue by duckmayr** [krlmlr/r-appveyor#135]
The most recent build of my [bggum](https://github.com/duckmayr/bggum) package (build link [here](https://ci.appveyor.com/project/duckmayr/bggum/builds/21871025])) failed when an update to `curl` was attempted; the relevant portion starts at [line 160](https://ci.appveyor.com/project/duckmayr/bggum/builds/21871025#L160) and you can see the error message at [line 290](https://ci.appveyor.com/project/duckmayr/bggum/builds/21871025#L290); here's an abbreviated reproduction:

```
+ Rscript -e 'options(repos=c(CRAN="https://cran.rstudio.com")); remotes::install_deps(dependencies = TRUE, type="both")'
askpass      (NA           -> 1.1         ) [CRAN]
backports    (1.1.2        -> 1.1.3       ) [CRAN]
callr        (3.0.0        -> 3.1.1       ) [CRAN]
clipr        (0.4.1        -> 0.5.0       ) [CRAN]
curl         (3.2          -> 3.3         ) [CRAN]
```
...
```
package 'curl' successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package 'curl'
Execution halted
Command exited with code 1
```

Perhaps it's related to issue #76 ? The difference here being that I am in no way trying to manually change or update the `curl` version; it's just part of the normal default dependency updating -- I think. Any tips on workarounds, or something to look into that I may have inadvertently messed up?

Thanks!

**Comment by duckmayr** [comment]
If anyone else encounters this issue, I was able to get around it by deleting the cache.

**Comment by hughjonesd** [comment]
I have this, and deleting the cache doesn't help! Again, I have no explicit dependency on curl, but it is pulled in as a recursive dependency of devtools itself, which is in Suggests: ...

**Comment by gaborcsardi** [comment]
Set `R_REMOTES_STANDALONE=true`, see https://github.com/r-lib/remotes#standalone-mode.

Then the installation will not use curl.
