### ISSUE TITLE
libpng, libjpeg, fftw3

### ISSUE THREAD

**Issue by jwijffels** [krlmlr/r-appveyor#136]
Are there any ways on providing similar things as libpng, libjpeg and fftw3 on appveyor like you can easily install on travis. I would like to use the headers of these and I'm not getting the following on appveyor: https://ci.appveyor.com/project/jwijffels/image/builds/22152019/job/8n6h91mne78ej378
```

  C:/Rtools/mingw_32/bin/gcc  -I"C:/R/include" -DNDEBUG  -I"c:/RLibrary/Rcpp/include"     -lpng -lz -fopenmp -L"C:/R/bin/i386" -lRlapack -L"C:/R/bin/i386" -lRblas -lgfortran -lm -lquadmath   -O3 -Wall  -std=gnu99 -mtune=generic -c io_png.c -o io_png.o
   io_png.c:44:17: fatal error: png.h: No such file or directory
    #include <png.h>
                    ^
   compilation terminated.
```

**Comment by krlmlr** [comment]
Maybe this will be easier with Rtools 4.0?

https://jeroen.github.io/rstudio2019/#22

It works on my machine, but I haven't tried on AppVeyor yet.

**Comment by jwijffels** [comment]
Gee, I wasn't aware of the extent of these slides untill now. What a great work!
