### ISSUE TITLE
Build check fails due to `contrib.url()` attempting to use CRAN without mirror

### ISSUE THREAD

**Issue by mjsteinbaugh** [krlmlr/r-appveyor#139]
Hi @krlmlr, I think I'm seeing a new error pop up for AppVeyor checking an R package that depends on Bioconductor:

```
+ Rscript -e 'if (getRversion() >= '\''3.5.0'\'') {if (!requireNamespace('\''BiocManager'\'', quietly=TRUE)) install.packages('\''BiocManager'\''); if (TRUE) BiocManager::install(version = '\''devel'\''); options(repos=BiocManager::repositories())} else {source('\''http://bioconductor.org/biocLite.R'\''); tryCatch(useDevel(TRUE), error=function(e) {if (!grepl('\''already in use'\'', e)) {e}}); options(repos=biocinstallRepos())}; library(devtools); install_deps(dependencies = TRUE, type="both")'
Installing package into 'c:/RLibrary'
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted
```

Here's a link to a recent build check log file where this error occurs:
https://ci.appveyor.com/api/buildjobs/nwpqkrbqpctc40py/log

**Comment by mjsteinbaugh** [comment]
I think it's related to this pull request being merged:
https://github.com/krlmlr/r-appveyor/pull/125

**Comment by krlmlr** [comment]
@LiNk-NY: Could you please take a look?

**Comment by LiNk-NY** [comment]
It sounds like it's from the build environment that doesn't have a default CRAN setting in `~/.Rprofile`. 
It was a similar issue on Travis CI: 
https://github.com/craigcitro/r-travis/issues/173

**Comment by LiNk-NY** [comment]
Usually you get something like by default in R:
```
getOption("repos")
    CRAN 
"@CRAN@"
```

Perhaps the `options(repos = ...)` should go first? 🤔

**Comment by LiNk-NY** [comment]
@mjsteinbaugh can you confirm the issue is resolved? Thanks!
