### ISSUE TITLE
503 error when build starts

### ISSUE THREAD

**Issue by wlandau** [krlmlr/r-appveyor#142]
Example [here](https://ci.appveyor.com/project/wlandau/drake/builds/22496334).

**Comment by javierluraschi** [comment]
Hitting this one as well

**Comment by msberends** [comment]
It’s because now GitHub forces the right domain:

https://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1

You have:

https://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1

This also needs to be changed in the sample file in this project, @krmlr

**Comment by krlmlr** [comment]
Closed in #140.
