### ISSUE TITLE
ERROR while "checking PDF version of manual without hyperrefs or index"

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#143]
I haven't gotten this error on `AppVeyor` before so not sure why I am suddenly getting this `ERROR` and `WARNING`.

```r
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in running tools::texi2pdf()
You may want to clean up by 'rm -Rf C:/Users/appveyor/AppData/Local/Temp/1/RtmpOMDfjo/Rd2pdf7b844d61afa'
* DONE
Status: 1 ERROR, 1 WARNING, 2 NOTEs
See
```

Plus, I am also getting the following `NOTE`-
```r
* checking top-level files ... NOTE
Files 'README.md' or 'NEWS.md' cannot be checked without 'pandoc' being installed.
```

**Comment by krlmlr** [comment]
Can you point to the build, please? Have you overridden `R_BUILD_ARGS` or `R_CHECK_ARGS` ?

**Comment by IndrajeetPatil** [comment]
Yes, here is a link to the build:
https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/builds/22535680/job/r5oc6adra48ks49y

**Comment by IndrajeetPatil** [comment]
Indeed, I have modified the yml as following-
https://github.com/IndrajeetPatil/ggstatsplot/blob/master/appveyor.yml

![image](https://user-images.githubusercontent.com/11330453/53149962-4b2dfd00-357d-11e9-8de4-7833a7271f21.png)

**Comment by krlmlr** [comment]
The override overwrite predefined arguments to `R CMD check` that hide this behavior. Do we need `R_CHECK_ARGS_EXTRA` ?
