### ISSUE TITLE
Error "Object 'false' not found" with the matrix Environment: R_VERSION=release, R_ARCH=x64, BIOC_USE_DEVEL=false, _R_CHECK_FORCE_SUGGESTS_=false

### ISSUE THREAD

**Issue by rohith008** [krlmlr/r-appveyor#150]
![Screen Shot 2019-05-03 at 3 13 41 PM](https://user-images.githubusercontent.com/33464256/57160516-f990c280-6db6-11e9-8bf1-941a3128ddee.png)

The build scripts for Bioconductor packages are failing. I have tried with "install_bioc" and "install_bioc_deps" which resulted in the error "Object false not found" when the BIOC_USE_DEVEL=false and "Object true not found" when the 
BIOC_USE_DEVEL=true.

**Comment by LiNk-NY** [comment]
Perhaps it should be all caps? TRUE, FALSE

**Comment by rohith008** [comment]
Yeah all caps worked, Thank you...!
