### ISSUE TITLE
Dependency successfully unpackaged but not available for package in Remotes

### ISSUE THREAD

**Issue by joethorley** [krlmlr/r-appveyor#152]
I have an R package on GitHub (https://github.com/poissonconsulting/dttr2) which includes 

```
Remotes:
    tidyverse/hms
```

in the DESCRIPTION (as it requires hms (>= 0.4.2.9003)).

It builds no problem on travis but I get the following error on Appveyor.

What's weird is that the dependencies are successfully unpackaged but then apparently not available.

```
279 package 'pkgconfig' successfully unpacked and MD5 sums checked
280 package 'rlang' successfully unpacked and MD5 sums checked
281 package 'vctrs' successfully unpacked and MD5 sums checked
282 package 'zeallot' successfully unpacked and MD5 sums checked
283
284 The downloaded binary packages are in
285	C:\Users\appveyor\AppData\Local\Temp\1\RtmpsvpcOY\downloaded_packages
286 Running `R CMD build`...
287 * checking for file 'C:\Users\appveyor\AppData\Local\Temp\1\RtmpsvpcOY\remotesa94740018da\tidyverse-hms-8dfd373/DESCRIPTION' ... OK
288 * preparing 'hms':
289 * checking DESCRIPTION meta-information ... OK
290 * installing the package to process help pages
291       -----------------------------------
292 ERROR: dependencies 'pkgconfig', 'rlang', 'vctrs' are not available for package 'hms'
```

The full console output is at <https://ci.appveyor.com/project/poissonconsulting/dttr2>.

What am I missing?

**Comment by jayhesselberth** [comment]
@krlmlr I'm seeing this issue too. Any ideas?

**Comment by krlmlr** [comment]
These appear to be two different issues.

@joethorley: Your builds seem to succeed now, have you seen this error recently?

@jayhesselberth. Weird. I'm seeing: "dependency 'Rcpp' is not available for package 'xml2'" in https://ci.appveyor.com/project/r-lib/pkgdown/builds/25555481#L635 . I wonder why Rcpp isn't installed before trying to compile xml2. Can you replicate this locally?

**Comment by joethorley** [comment]
@krlmlr I fixed it by no longer depending on the development version of hms.

**Comment by krlmlr** [comment]
Closing for now, please open a new issue if needed.
