### ISSUE TITLE
"unable to access index for repository" error

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#158]
With the new updates, my [builds](https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/build/job/aufkliqkbu596oy2) are now failing with the following message-
```r
Installing packages into 'c:/RLibrary'
(as 'lib' is unspecified)
Error: (converted from warning) unable to access index for repository wininet/bin/windows/contrib/3.6:
  scheme not supported in URL 'wininet/bin/windows/contrib/3.6/PACKAGES'
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*

```

**Comment by krlmlr** [comment]
This is what I'm seeing too with R 3.2. Working on it.

Thanks for confirming it fails with other versions!

**Comment by krlmlr** [comment]
I think this is fixed now, can you confirm?

**Comment by IndrajeetPatil** [comment]
Yes, it is fixed now! Thanks.
