### ISSUE TITLE
source versions of packages no longer installed?

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#159]
I pushed [this commit](https://github.com/IndrajeetPatil/ggstatsplot/commit/8b6de18104127d7412adae02df7e87ee24679b78)  and only `AppVeyor` (but not `Travis`) builds are [failing](https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/builds/25793136/job/aq3my8ayhlb6vrlg) because I increased `dplyr` version from `0.8.2` to `0.8.3`-

```r
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Package required and available but unsuitable version: 'dplyr'
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
* DONE
Status: 1 ERROR, 1 NOTE
See
  'C:/projects/ggstatsplot/ggstatsplot.Rcheck/00check.log'
for details.
Command exited with code 1
7z a failure.zip *.Rcheck\*
```
Is this because the new changes made no longer make it possible to download the source versions of R packages, like before?

![image](https://user-images.githubusercontent.com/11330453/60760661-253f5b80-a039-11e9-8b27-6acd4c0d98bf.png)

**Comment by krlmlr** [comment]
It's very likely. Set `PKGTYPE` to `both` if you need the latest and greatest.

We've moved away from setting requirements to the most recent package versions, and try to import the minimum really required versions. See https://github.com/krlmlr/minver/ for a workflow to find out which versions your package really needs.

**Comment by IndrajeetPatil** [comment]
Thanks, that solved it.

**Comment by IndrajeetPatil** [comment]
@krlmlr Why do my builds fail even when I have set `PKGTYPE` to `both`?

https://github.com/IndrajeetPatil/ggstatsplot/blob/e0f2c2d3963e4b66dd49f85a5233122c8505b7e1/appveyor.yml#L19-L39

For example, [this](https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/build/job/4kv3fhpdnhij0q1t) build fails because `Rcpp`'s source version can't be downloaded-

```r
* installing *source* package 'rcompanion' ...
** package 'rcompanion' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'rcompanion'
* removing 'c:/RLibrary/rcompanion'
Error in i.p(...) : 
  (converted from warning) installation of package 'rcompanion' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*

```
