### ISSUE TITLE
cannot remove prior installation of package 'curl'

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#163]
My builds are failing with the following error:
https://ci.appveyor.com/project/IndrajeetPatil/ggstatsplot/builds/26897246/job/ig46eho74h8222qb

```r
package 'curl' successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package 'curl'
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*
```

**Comment by krlmlr** [comment]
Can you please try turning off the cache? Installation of binary packages is very fast.

**Comment by IndrajeetPatil** [comment]
Thanks for the suggestion.

Which of these two options should I choose to turn off cache? Or both of them?

![image](https://user-images.githubusercontent.com/11330453/63590673-8b952480-c57a-11e9-96e2-6b72826f2730.png)

**Comment by pat-s** [comment]
Alternatively, setting `R_REMOTES_STANDALONE=true` should help, see https://github.com/krlmlr/r-appveyor/issues/135
