### ISSUE TITLE
Error: package 'remotes' was installed before R 4.0.0: please re-install it

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/r-appveyor#179]
All my recent `AppVeyor` builds are failing with the following error:

![image](https://user-images.githubusercontent.com/11330453/80287426-d8e11b80-8731-11ea-9fb9-fb5a08846d02.png)

**Comment by gaborcsardi** [comment]
I believe that you need to purge your cache.

**Comment by IndrajeetPatil** [comment]
Thanks, that worked!

For someone else who might run in the same issue, here is how to clear cache for AppVeyor builds:
https://www.appveyor.com/docs/build-cache/#cleaning-up-cache
