### ISSUE TITLE
Support different versions of R

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-appveyor#2]
By environment variable, so that this can also be done in a build matrix.

- [ ] By version number
- [ ] `stable`
- [ ] `devel`

**Comment by jread-usgs** [comment]
:+1: this would be amazingly helpful if possible.

**Comment by krlmlr** [comment]
@jread-usgs: Much easier now since there's also R 3.2.0 on the image (https://github.com/krlmlr/r-portable/commit/2f27b665e0a619c95ef3fb8f14c3eb495fb3da32). Would you like to help with a pull request that enables choosing the version of R (e.g., via environment variable)?

**Comment by jread-usgs** [comment]
I think I can help, although I would probably need some back-and-forth. Is there a pattern elsewhere you would like to follow? `r-builder` or something else?

**Comment by krlmlr** [comment]
Currently the project is using the old `travis-tool.sh`. Good idea to move to r-builder, actually -- but I'm not sure what the effort is nor if it's possible to do in a backward-compatible way.

**Comment by gaborcsardi** [comment]
Also, r-builder is changing a lot more than travis-tool nowadays....

**Comment by krlmlr** [comment]
After re-reading the source, I think the two issues are orthogonal:

- Setting the `PATH` to R is done in `appveyor-tool.ps1`
- Downloading the `travis-tool.sh` is also done in `appveyor-tool.ps1` but this would not affect the choice of the R version

This means that for choosing a different R version the code that sets `PATH` should be sensitive to some environment variable or even parameter. To me, an environment variable looks most practical, because this permits a [build matrix](http://www.appveyor.com/docs/build-configuration#build-matrix) for both R-stable and R-devel.

Now, there really seems to be no reason why `pkg-build.sh` should not be included in the r-portable image. If we do this, we can slowly phase out the usage of `travis-tool.sh` by recommending the new syntax in the `devtools` template. But again, I think this is a separate issue.

**Comment by jread-usgs** [comment]
@krlmlr how would you like to proceed given what you mention above?

**Comment by krlmlr** [comment]
@jread-usgs: I'd be happy to merge a pull request that allows an optional environment variable to set the `PATH` to R, which is now [hard-coded](https://github.com/krlmlr/r-appveyor/blob/a7df77639ed96ddff1110c6b0375f7bd8bce99f8/scripts/appveyor-tool.ps1#L82).

**Comment by jread-usgs** [comment]
Thanks @krlmlr this looks doable, but I am just about to take a vacation for ~12 days. Hope it is ok to work on after I return.

**Comment by lawinslow** [comment]
This would be great. If a simple environment variable were supported, then you could use it in a [build matrix](http://www.appveyor.com/docs/build-configuration#build-matrix) to run multiple versions of R for each build.

**Comment by lawinslow** [comment]
@krlmlr Who is maintaining the [R vhd file](https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1#L59)? Is this something you are manually creating and storing on Azure? I am trying to figure out where the vhd's of different versions would come from (to generate the correct URL).

**Comment by jread-usgs** [comment]
Aren't all the versions in one VHD file?

**Comment by lawinslow** [comment]
Not at the moment. Currently holds R-unstable and R-unstable. Would support 2 and 3 above, but still need other versions by number. 
![image](https://cloud.githubusercontent.com/assets/347600/7592204/a5e0e608-f897-11e4-9c68-274f62dcd61f.png)

**Comment by krlmlr** [comment]
See https://github.com/krlmlr/r-portable/issues/4 for the project and the issue that describes multiple R versions. @lawinslow: Did you mean r-unstable and r-stable?

**Comment by lawinslow** [comment]
Ha, yeah, that's what I meant.

**Comment by krlmlr** [comment]
If more than that is to be supported, probably the only way to go is to create individual images for different R versions -- R is not that small after all. For now it's those two versions of R.

**Comment by lawinslow** [comment]
Hmmm, my first thought here is to see if r-oldrel could be worked into this too. That way we'd always be able to cover the same range of R versions that CRAN supports (Any thoughts on this? I'd be happy to PR both r-portable and r-appveyor). 

But one challenge there is that technically, one Rtools version technically [wouldn't cover the full range](http://cran.r-project.org/bin/windows/Rtools/). I'm not sure how much that matters though. Hmmmm.
