### ISSUE TITLE
 'qpdf' is needed for checks on size reduction of PDFs 

### ISSUE THREAD

**Issue by qinwf** [krlmlr/r-appveyor#24]
Thanks for this great project!

I just came across this  WARNING only on AppVeyor:

``` 
WARNING  'qpdf' is needed for checks on size reduction of PDFs 
```

Here is the full result https://ci.appveyor.com/project/qinwf53234/jiebar/build/1.0.7

**Comment by krlmlr** [comment]
Not building vignettes for now. I think this error is related to a glitch in R CMD check: https://stat.ethz.ch/pipermail/r-devel/2015-October/071917.html
