### ISSUE TITLE
Windows package Zip dowloadable?

### ISSUE THREAD

**Issue by berndbischl** [krlmlr/r-appveyor#28]
Hi,

is it somehow possible to access / link to the windows zip file which is built before the check on appveyor?

I am asking as I would like to give that as an easy-to-provide devel built to windows users.

**Comment by krlmlr** [comment]
Is there an "Artifacts" link on the build page? See e.g. https://ci.appveyor.com/project/krlmlr/r-appveyor/build/artifacts .

**Comment by berndbischl** [comment]
Yes there is and sorry for my late reply.

It seems to be a bit unfortunate that for the "latest build" URL there is a hash in the URL. 
So it is not simple to link to the ZIP directly? 

But I can live with that.
