### ISSUE TITLE
Publish to drat repositories

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-appveyor#29]
http://www.appveyor.com/docs/how-to/git-push

**Comment by JanSchulz** [comment]
It would also be nice if there would be a way to build with different R versions.

**Comment by krlmlr** [comment]
@JanSchulz: I think your request is covered by #2. Contributions welcome!

**Comment by nfultz** [comment]
For whatever it's worth, we (DeclareDesign) have been pushing appveyor builds to drat for a  month, although there was a sneaky bug in drat that had to be fixed first.

**Comment by krlmlr** [comment]
There is a tic-based example in https://github.com/ropenscilabs/tic. I think it's out of scope for this project.
