### ISSUE TITLE
Installation from bioconductor

### ISSUE THREAD

**Issue by sckott** [krlmlr/r-appveyor#30]
Doesn't seem to work for me now. E.g., `sangerseqR` used to install on appveyor, but now it errors: 

https://ci.appveyor.com/project/sckott/bold/build/1.0.260#L1038

It's definitely in the appveyor file: 

https://github.com/ropensci/bold/blob/master/appveyor.yml#L12

Any thoughts/advice on this?

**Comment by krlmlr** [comment]
Package `Biostrings` seems to be required but cannot be installed:

https://ci.appveyor.com/project/sckott/bold/build/1.0.260#L975

I have no idea what this is or why it worked before.

**Comment by sckott** [comment]
thanks @krlmlr - I'll keep digging

**Comment by krlmlr** [comment]
I've seen other hints, much earlier:

>     WARNING: Rtools 3.3 found on the path at e:/Rtools is not compatible with R 3.3.0.
>     Bioconductor does not yet support R version 3.3.0

I'll check the Rtools issue, but I'm not sure how to fix the Bioconductor message. Could be wiser to move to R-stable for AppVeyor testing...

**Comment by sckott** [comment]
@krlmlr sounds good to use R-stable. how do i use that?

**Comment by krlmlr** [comment]
We'd need an image for that, currently it's only R-devel. See https://github.com/krlmlr/r-portable/issues/4.

**Comment by krlmlr** [comment]
The Rtools compatibility warning has been fixed in https://github.com/hadley/devtools/commit/6fe9509c80cd7a51f5c1275e3ee4aa80b7659f28.
