### ISSUE TITLE
Take advantage of build caching

### ISSUE THREAD

**Issue by jimhester** [krlmlr/r-appveyor#31]
Appveyor supports caching of build dependencies (http://www.appveyor.com/docs/build-cache).

For CRAN dependencies they could then be selectively updated with `update.packages()`, which would then invalidate and update the cache.

Github dependencies would need some other form of updating, I guess, as drat use is not widespread.

**Comment by krlmlr** [comment]
Caching seems to require a copy from/to Azure storage, both before and after building. This slows down the build and diminishes potential benefits. Installing a binary package on Windows is *fast*, and I don't have much hope that caching will further improve this. It's different for source packages, but r-appveyor could help providing binary builds via drat (#29), making source installs unnecessary.

Do you have experience with AppVeyor caching?

**Comment by jimhester** [comment]
I do not have experience with it and that is true about binary builds on windows, I'll close this.

**Comment by krlmlr** [comment]
Important for testing R 3.4.0.

**Comment by krlmlr** [comment]
Should be added to the devtools template, too.

**Comment by mlt** [comment]
It would be nice to cache R & RTools installers to avoid re-downloading again and again.

**Comment by krlmlr** [comment]
The cache is limited to 100 MB, can't cache R. (Download + install of R takes just under 30 seconds now, I guess we'll have to live with that.)

**Comment by mlt** [comment]
It is 100 MB per cache entry IIRC. While it is a bummer with RTools (103Mb as I just checked for 3.4.x), R exes should be cacheable (~70MB).
