### ISSUE TITLE
issues with install_github?

### ISSUE THREAD

**Issue by jread-usgs** [krlmlr/r-appveyor#33]
Hi @krlmlr thank you so much for your support of r-appveyor. 

We are running into a new issue with install_github for package dependencies: 

for R-unstable:
https://ci.appveyor.com/project/jread-usgs/mda-streams/build/0.1.183#L140
and R-stable (3.2.0)
https://ci.appveyor.com/project/jread-usgs/mda-streams/build/0.1.179#L309

Do you know if this is a devtools issue or part of appveyor permissions that may have changed?

Thanks

**Comment by krlmlr** [comment]
Hi @jread-usgs 

Thanks for reporting this. It looks like AppVeyor has hit some limit on GitHub. Please ping me if the problem doesn't disappear tomorrow.

**Comment by masalmon** [comment]
So is this supposed to happen from time to time because of GitHub limits for AppVeyor? I encountered a similar issue today.

Thanks anyway for the repo. :-)

**Comment by gaborcsardi** [comment]
@masalmon Yes, you can work around this by getting a GitHub token, and then adding it to Appveyor as a secret `GITHUB_PAT` environment variable.

**Comment by masalmon** [comment]
Thanks a lot @gaborcsardi ! This was very helpful!
I'll write the steps in a dumb-proof way (I'm the dumb tester :-) ) for future reference:
- get a personal access token from Github (in Github settings)
- encrypt the token in appveyor following https://www.appveyor.com/docs/build-configuration#secure-variables 
- in appveyor.yml, add
"environment:
  GITHUB_PAT:
    secure: <encrypted value of the personal access token>"

**Comment by krlmlr** [comment]
Does it also work if you set `GITHUB_PAT` in the AppVeyor web interface?

**Comment by masalmon** [comment]
@krlmlr where exactly in the AppVeyor web interface?

**Comment by krlmlr** [comment]
Settings -> Environment -> Add variable

**Comment by masalmon** [comment]
Ok this makes sense, sorry, I thought it would be a global thing. If I did this I would still have to add the variable for each project, so it would not be a real gain compared to having the variable in appveyor.ylm, would it?

**Comment by krlmlr** [comment]
GitHub's PAT is personal, and you probably want to encrypt it -- you'll have to add it for each repo anyway.

**Comment by masalmon** [comment]
Yes which is what I do now (putting the encrypted PAT in all my appveyor.yml). You mean the gain of adding it via the interface simply is the fact that I wouldn't have to encrypt it?

**Comment by krlmlr** [comment]
IMO, the gain is that you don't pollute the .yml, but I'm not sure if this is really simpler than editing appveyor.yml once for all projects. Anyway, I've added an external GITHUB_PAT to one of my projects, if I ever hit the rate limit with this, we know it doesn't work.

**Comment by masalmon** [comment]
Ok, thanks!
