### ISSUE TITLE
Build with Github Package Dependency?

### ISSUE THREAD

**Issue by cdeterman** [krlmlr/r-appveyor#35]
Is there a way to install dependencies that are on github (e.g. a dev version of a package)?  I know with the Travis CI support one would use `r_github_packages`.  Is there a way to accomplish the same thing with r-appveyor?

**Comment by gaborcsardi** [comment]
Yes, it works the same way, as old Travis, it actually uses the same code. Here is an example: https://github.com/gaborcsardi/ask/blob/master/appveyor.yml#L16

**Comment by cdeterman** [comment]
Excellent, I wasn't sure what functionality was built in and I couldn't find an example like that.  Thank you.

**Comment by wibeasley** [comment]
FWIW, I believe that httr needs to follow install_deps.  But the order doesn't seem to matter with other packages.  (https://github.com/hadley/httr/issues/319)

```sh
build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github hadley/httr
```

(Thank you @gaborcsardi, your answer here really helped me get back on track.)

**Comment by gaborcsardi** [comment]
@wibeasley `devtools` depends on `httr` and appveyor installs `devtools` first (maybe even caches a binary for it), so maybe that is the problem.

In general it is actually better to call `install_github` first, because `install_deps` might simply fail if a dependency is not available from CRAN.

**Comment by wibeasley** [comment]
Thanks @gaborcsardi, I'll keep that order in mind.  I guess the rule of thumb is to place `install_github zzzz/zzzzz` before `install_deps`, unless something like this happens.

That's interesting about caching.  I hadn't thought of that.

**Comment by krlmlr** [comment]
I'm not consciously using any cache in AppVeyor, but there might be a caching proxy server I'm not aware of. Installing binary packages on Windows is just *fast* anyway, as is downloading them from RStudio's CRAN server.

**Comment by wibeasley** [comment]
*Followup for anyone finding this through a search engine*: The [403 error was probably related to networking](https://github.com/hadley/httr/issues/319#issuecomment-171083155), and not to `appveyor.yml`.

**Comment by privefl** [comment]
Sorry to post in this closed issue.
But, do we need this `travis-tool.sh install_github repo/pkg` even if we have this `repo/pkg` listed in the `Remotes` field of the DESCRIPTION file?

**Comment by krlmlr** [comment]
@privefl: For compatibility with older setups that don't use `Remotes` yet.
