### ISSUE TITLE
Noisy output due to dump of log files

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-appveyor#37]
Artifacts are not normally archived with failed builds. Perhaps artifacts can be pushed manually: http://www.appveyor.com/docs/packaging-artifacts. This would avoid the necessity to dump logs.

CC @hadley

Example: https://ci.appveyor.com/project/hadley/devtools/build/1.0.10#L360

**Comment by krlmlr** [comment]
I think this is better handled by AppVeyor, for now we can search the output for "dump", that's where the clutter begins -- the reason for failure should be shown just before that.

**Comment by HenrikBengtsson** [comment]
FYI, and related to http://help.appveyor.com/discussions/suggestions/828-store-some-artifacts-in-case-of-failure, I've ended up using:
```
on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
```
See also example [log](https://ci.appveyor.com/project/HenrikBengtsson/matrixstats/build/1.0.217) and [artifacts](https://ci.appveyor.com/project/HenrikBengtsson/matrixstats/build/1.0.217/artifacts).

**Comment by krlmlr** [comment]
Thanks, Henrik, this looks like a very useful workaround!

**Comment by krlmlr** [comment]
This is fixed in the devtools template now.
