### ISSUE TITLE
Problem with Rtools

### ISSUE THREAD

**Issue by sckott** [krlmlr/r-appveyor#38]
Anyone else having this problem?  https://ci.appveyor.com/project/sckott/musemeta/build/1.0.362#L23 

> Failed to mount Rtools. Could not find directory: :\Rtools\bin

**Comment by krlmlr** [comment]
Sorry for this. I have yet to figure out a solution that works with the upgraded Rtools. Will post updates here.

**Comment by sckott** [comment]
thanks!

**Comment by krlmlr** [comment]
Thanks for your patience. Everything seems well now, please feel free to comment and/or reopen if further problems arise.

The r-portable image has been split, now there's an image for R, and another for Rtools (https://github.com/krlmlr/rtools-portable). The full image was just too large to be built before hitting the AppVeyor timeout.

**Comment by sckott** [comment]
awesome, thanks!
