### ISSUE TITLE
ErrorActionPreference error on build

### ISSUE THREAD

**Issue by leeper** [krlmlr/r-appveyor#39]
I just started getting the following error [on this build](https://ci.appveyor.com/project/leeper/rio/build/1.0.22):

```
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: System.Management.Automation.RemoteException
```

Any idea how to solve that?

**Comment by krlmlr** [comment]
Thanks for pinging me, and sorry for the trouble. This is a temporary issue with my storage service provider which should auto-resolve tomorrow. Please feel free to nudge me if it doesn't.

**Comment by leeper** [comment]
No problem at all. Thanks!

**Comment by sckott** [comment]
Thanks @krlmlr

**Comment by jread-usgs** [comment]
:+1:

**Comment by jread-usgs** [comment]
Just a heads up, this issue seems to be popping up again. @krlmlr I really appreciate your work on this, but wanted to let you know. e.g., https://ci.appveyor.com/project/jread-usgs/geoknife/branch/master

**Comment by krlmlr** [comment]
Thanks, should be working now. Please feel free to open a new issue if this occurs again.

**Comment by jread-usgs** [comment]
Thanks! :+1:
