### ISSUE TITLE
Don't download Rtools

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-appveyor#40]
if there is no `src/` directory, to save on build time and bandwidth.

**Comment by HenrikBengtsson** [comment]
I'm just trying upgrade to a modern version of r-appveyor and things seem to work out of the box.  However, my [package does not have a `src/` directory](https://github.com/HenrikBengtsson/R.devices/tree/develop) but `r-appveyor` is [still downloading and installing Rtools](https://ci.appveyor.com/project/HenrikBengtsson/r-devices/build/1.0.59);
```
[...]
[1] stats     graphics  grDevices utils     datasets  base     
== 03/08/2016 21:52:59: Determining Rtools version 
== 03/08/2016 21:53:01: Downloading Rtools from: https://cran.rstudio.com/bin/windows/Rtools/Rtools33.exe 
== 03/08/2016 21:53:14: Running Rtools installer 
Rtools is now available on drive C:
== 03/08/2016 21:56:14: Setting PATH 
== 03/08/2016 21:56:14: Downloading and installing travis-tool.sh 
```

Could there be something wrong with https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1#L150-L155:
```sh
  if ( Test-Path "/**/src" ) {
    InstallRtools
  }
  Else {
    Progress "Skipping download of Rtools because src/ directory is missing."
  }
```

**Comment by PolMine** [comment]
Dear colleagues,
maybe making the installation of Rtools optional causes other appveyor problems. When checking my package cwbtools (github.com/PolMine/cwbtools), I get an error that g++ is missing:

```
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
** libs
*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"c:/R/include" -DNDEBUG -I. -Iicu61/ -Iicu61/unicode -Iicu61/common -Iicu61/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL -DU_TOOLUTIL_IMPLEMENTATION -DNDEBUG -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DU_USE_STRTOD_L=0         -O2 -Wall  -mtune=generic -c stri_ICU_settings.cpp -o stri_ICU_settings.o
/bin/sh: c:/Rtools/mingw_32/bin/g++: No such file or directory
make: *** [stri_ICU_settings.o] Error 127
ERROR: compilation failed for package 'stringi'
* removing 'c:/RLibrary/stringi'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package 'stringi' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*
```
My interpretation is that appveyor recognizes that Windows binaries at CRAN are much older than the latest Package source. This is what I see at CRAN (https://cran.r-project.org/web/packages/stringi/index.html).

```
Reference manual: | stringi.pdf
Package source: | stringi_1.2.4.tar.gz
Windows binaries: | r-devel: stringi_1.1.7.zip, r-release: stringi_1.1.7.zip, r-oldrel: stringi_1.1.7.zip
OS X binaries: | r-release: stringi_1.2.4.tgz, r-oldrel: stringi_1.2.4.tgz
Old sources: | stringi archive
```
So this is why Appveyor tries to compile stringi, which results in an error? 

If this is the case, then making the installation of Rtools optional on the presence of a src directory of the package that is tested might frequently result in errors of the kind I see. 

I am not an expert on this - I just wanted to share my interpretation.

Kind regards
Andreas (Blätte)

**Comment by krlmlr** [comment]
You can always force installation of Rtools, see README.

It's very strange that _stringi_ binaries lag that much.

In the future, could you please open a new issue? Comments on an old issue are easy to miss.
