### ISSUE TITLE
bin/sh: g++: command not found

### ISSUE THREAD

**Issue by wush978** [krlmlr/r-appveyor#41]
Hi,

I am using `sourceCpp` in my unit tests of R package. But the compilation failed because the `g++` is not found.

Here is the build log: <https://ci.appveyor.com/project/wush978/rcereal/build/1.0.29>

I also dump the PATH:  <https://ci.appveyor.com/project/wush978/rcereal/build/1.0.29#L425>, but cannot see any error there.

**Comment by krlmlr** [comment]
As of yesterday, the presence of the `src/` directory triggers download of R-tools (#40). Your package doesn't seem to have such a directory, and to me it seemed unusual to require a C++ compiler if there is no `src/` directory. Would you mind simply adding an empty `src/` directory, perhaps with an empty `.gitignore` file? I am open to other suggestions.

**Comment by krlmlr** [comment]
Build log reference: https://ci.appveyor.com/project/wush978/rcereal/build/1.0.29#L25.

**Comment by wush978** [comment]
Got it. I'll create an empty directory `src/` in the package.

Thanks!
