### ISSUE TITLE
GCC missing?

### ISSUE THREAD

**Issue by hofnerb** [krlmlr/r-appveyor#45]
In my AppVeyor project I get the following error at check time:

```
checking whether package 'mboost' can be installed ...Warning: running command '"d:/R/bin/i386/Rcmd.exe" INSTALL -l "C:/projects/mboost/pkg/mboostPatch/mboost.Rcheck" --build --no-html "C:\projects\mboost\pkg\MBOOST~2\MBOOST~1.RCH\00_PKG~1\mboost"' had status 1
 ERROR
Installation failed.
See 'C:/projects/mboost/pkg/mboostPatch/mboost.Rcheck/00install.out' for details.
```

00install.out shows the following error:
```
* installing *source* package 'mboost' ...
** libs
 
*** arch - i386
gcc -m32 -I"d:/R/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local323/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c mboost.c -o mboost.o
/bin/sh: gcc: command not found
make: *** [mboost.o] Error 127
Warning: running command 'make -f "Makevars" -f "d:/R/etc/i386/Makeconf" -f "d:/R/share/make/winshlib.mk" SHLIB="mboost.dll" OBJECTS="mboost.o"' had status 2
ERROR: compilation failed for package 'mboost'
```

I am not exactly sure why this happens. Is gcc really missing or just expected in the wrong place? And how can I solve this?

**Comment by krlmlr** [comment]
I limited Rtools downloads to only those projects that seem to need it. I though [testing for a src/ directory](https://github.com/krlmlr/r-appveyor/blob/3719f6bd0f3ed510003cca922663739af6aaf469/scripts/appveyor-tool.ps1#L77) is robust enough, but obviously it doesn't work if the package is in a subdirectory of the repository.

I think the easiest solution here is to override the test with an environment variable (download Rtools if src/ exists or if an environment variable is set to nonzero). I'll be happy to review a pull request.

**Comment by hofnerb** [comment]
Now that I read your reply I do remember that feature. Thanks for the clarification. 

I really would like to contribute a patch, however, I have no experience in what I guess is PowerShell. I will see if I can deduce the relevant details from other code parts. However, if anyone knows how to do it in the first place I would be really thankful. In any case I am more than happy to test the script in my repository. [And yes, I should change the structure soon :)]

**Comment by krlmlr** [comment]
I'd have to look it up, too -- my PowerShell experience is rather limited as well...
