### ISSUE TITLE
Extra cran mirror for ncdf4

### ISSUE THREAD

**Issue by sckott** [krlmlr/r-appveyor#47]
trying to get `ncdf4` binaries to install on a build - but they're only avail. on Ripley's cranextra mirror http://www.stats.ox.ac.uk/pub/RWin

I assumed I set `R_LIBS` env var, but i either didn't set that right, or there's a different way to do it?

**Comment by krlmlr** [comment]
Sorry, missed that. Perhaps you need a call to `options(repos = ...)` somewhere before installing it (via `Rscript -e`)?

Adding that extra repo by default sounds like a good idea, too.

**Comment by sckott** [comment]
Thanks, I'll try a call to `options(repos)` -

**Comment by krlmlr** [comment]
Were you successful with setting R_LIBS? What would I need to do to make this the default?

**Comment by sckott** [comment]
Seems to be working now e.g.,  https://travis-ci.org/ropensci/rerddap/builds/102385912#L1167-L1235

I think they do have binaries on the main CRAN mirrors now

**Comment by krlmlr** [comment]
You linked to Travis, I was asking about the Windows build... But I see that ncdf4 binary is on CRAN too. Can we close this?

**Comment by sckott** [comment]
ah, woops, sorry, Just checked and yes the appveyor projects that use `ncdf4` are working. 

yes, close
