### ISSUE TITLE
r-appveyor builds failing almost immediately

### ISSUE THREAD

**Issue by cdeterman** [krlmlr/r-appveyor#51]
I have had much success using r-appveyor but suddenly my builds are crashing shortly after they start referring to the `appveyor-tool.ps1` file.  And example where this is taking place can be seen [here](https://ci.appveyor.com/project/cdeterman/gpur/build/1.0.95).  Any idea what is happening?

**Comment by krlmlr** [comment]
Thanks for nudging me, should be working now.

**Comment by cdeterman** [comment]
It indeed appears to be working now.  Thanks!
