### ISSUE TITLE
Interested in contributing to an API package?

### ISSUE THREAD

**Issue by leeper** [krlmlr/r-appveyor#52]
Just wanted to draw your attention to my efforts here: https://github.com/cloudyr/appveyor to create an API client for appveyor (basically to be able to control and configure builds remotely from R). It's missing documentation, though.

Let me know if you're interested in joining on to it.

**Comment by krlmlr** [comment]
Thanks for inviting me. Unfortunately, I'm not familiar with the AppVeyor API, my contributions there will be of limited value. I'll gladly take feedback on the r-appveyor project, though: For instance, perhaps the builds can be organized in a way that faciliates the consumption of the results by cloudyr.

**Comment by leeper** [comment]
Sounds good. Just wanted to make sure you felt welcome to get involved.
