### ISSUE TITLE
Skipping download of Rtools because src/ directory is missing.

### ISSUE THREAD

**Issue by sckott** [krlmlr/r-appveyor#55]
I get that message on this build https://ci.appveyor.com/project/sckott/finch/build/1.0.426#L35

and later failure because rtools not installed, trying to install dev version of `data.table` from github

any idea about this?

**Comment by krlmlr** [comment]
Rtools is not installed if the package is missing a `src` directory (#54). I think you can override this by creating an empty "src" directory (in appveyor.yml); I'm open to pull requests that control this with an environment variable.

AFAIK, data.table has a drat repo. Perhaps they could push there binary versions using r-appveyor (#29)?

**Comment by sckott** [comment]
> I'm open to pull requests

okay, will have a look

> AFAIK, data.table has a drat repo. 

right, they do have one

**Comment by hofnerb** [comment]
What do I need to put in my appveyor.yml file in order to create the empty dir and more importantly where? (I'd guess `mkdir src` but I do not know where and how exactly)
