### ISSUE TITLE
Add support for BiocCheck

### ISSUE THREAD

**Issue by richierocks** [krlmlr/r-appveyor#65]
For checking packages to be submitted to Bioconductor, as well as `R CMD check`, you also need to run `R CMD BiocCheck`. See:

https://www.bioconductor.org/packages/release/bioc/html/BiocCheck.html

The [Vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html) gives the setup and usage details.

It would be great if you could run `BiocCheck` by specifying some settings in the `appveyor.yml`.  (Since most of the checks aren't Bioconductor-specific, this is pretty useful even if you only develop for CRAN.)

You can install the `BiocCheck` package using:

```
build_script:
 - travis-tool.sh install_bioc BiocCheck
```

I can't see a way to actually call `BiocCheck` and parse the results.  

(It's also not totally clear to me whether this issue belongs here or in @craigcitro's [r-travis](https://github.com/craigcitro/r-travis) project.)

See also https://github.com/metacran/r-builder/issues/47

**Comment by krlmlr** [comment]
The r-travis project is obsolete, I'm working on integrating the relevant scripts in this repository (#74).

**Comment by krlmlr** [comment]
BioConductor support added by @LiNk-NY (thanks!), please open a new issue if necessary.
