### ISSUE TITLE
RcppEigen missing?

### ISSUE THREAD

**Issue by cdeterman** [krlmlr/r-appveyor#66]
I have been having a [build](https://ci.appveyor.com/project/cdeterman/gpur/build/1.0.183) consistently failing because the `RcppEigen` package is always missing.  I looked at the rstudio mirror and it appears that `RcppEigen` is there.  Any ideas why this would be happening with appveyor?

**Comment by cdeterman** [comment]
I have since realized this is being addressed in a previously closed [issue](https://github.com/krlmlr/r-appveyor/issues/57#issuecomment-220848950)

**Comment by krlmlr** [comment]
Right, sorry I missed your report.
