### ISSUE TITLE
Shallower clone?

### ISSUE THREAD

**Issue by hannesmuehleisen** [krlmlr/r-appveyor#67]
The travis version of this does not clone the entire repo history (--depth) and is thus faster. Could this be an option here, too? Or is it already?

**Comment by krlmlr** [comment]
I think you have to [opt in](https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories).

**Comment by hannesmuehleisen** [comment]
nope that made no difference

**Comment by krlmlr** [comment]
Did you update appveyor.yml? In any case, cloning is done by AppVeyor, so there's not much we can do here.

**Comment by hannesmuehleisen** [comment]
ok thanks
