### ISSUE TITLE
Set _R_CHECK_FORCE_SUGGESTS_ to FALSE

### ISSUE THREAD

**Issue by jeroen** [krlmlr/r-appveyor#72]
CRAN sets `_R_CHECK_FORCE_SUGGESTS_=0` in their checks because some suggests might not be available on Windows, but the check still passes. I have the same problem with e.g. protolite: https://ci.appveyor.com/project/jeroenooms/protolite

```
* checking package dependencies ... ERROR
Package suggested but not available: 'RProtoBuf
```

I think it would make sense to default to `_R_CHECK_FORCE_SUGGESTS_=0` on AV as well?

**Comment by krlmlr** [comment]
Interesting. But what are the effects if `_R_CHECK_FORCE_SUGGESTS_=0` is the default and the tests are not prepared for missing suggested packages? The error message is rather self-explanatory now, and it's easy to fix on the client side.

**Comment by jeroenooms** [comment]
If this is the case you get a `NOTE` (rather than `ERROR`) during CMD check:

```
* checking package dependencies ... NOTE
Package suggested but not available for checking: ‘RProtoBuf’
```

And then if the package is actually required it just errors where the package is used:

```r
Error in library("RProtoBuf") : there is no package called ‘RProtoBuf’
```

**Comment by krlmlr** [comment]
I'd rather not set this globally, but add a pointer to this setting in the README and suggest using this in a build matrix.

**Comment by krlmlr** [comment]
OTOH, this is now the default setting for `travis::use_tic()`, so I guess it should be the default. @jimhester: Do/should we have `_R_CHECK_FORCE_SUGGESTS_` off by default on Travis?

**Comment by krlmlr** [comment]
Fixed by documentation.
