### ISSUE TITLE
Can't use development version of curl package: Permission to copy a file

### ISSUE THREAD

**Issue by synikitin** [krlmlr/r-appveyor#76]
I need a development version of curl for a package, but it seems like I cannot overwrite the default curl when attempting install from github: 
https://ci.appveyor.com/project/slavaua87/cognizer

**Comment by krlmlr** [comment]
I'd guess that this is because devtools, which is used to install from GitHub, imports the curl package; this loads and locks the DLL and causes the behavior you're seeing.

Perhaps @jeroenooms or @jimhester know a workaround?

**Comment by jeroenooms** [comment]
To any package from github without devtools just give it the URL:

```r
install.packages("https://github.com/jeroenooms/curl/archive/stable.tar.gz", repos = NULL)
install.packages("https://github.com/jeroenooms/openssl/archive/master.tar.gz", repos = NULL)
install.packages("https://github.com/jeroenooms/jsonlite/archive/master.tar.gz", repos = NULL)
```

**Comment by gaborcsardi** [comment]
@jeroenooms I don't think this is good in general, because it does not run `R CMD build`, so `.Rbuildignore` is ignored, `cleanup` is not run, etc. Maybe it works for your packages, but not always.

**Comment by jeroenooms** [comment]
@gaborcsardi ok good point, thanks. But at least it should work for devtools dependencies, which you cannot install with devtools (at least not on windows).

**Comment by slavaua87** [comment]
Right now, the curl install is initiated through Remotes: jeroenooms/curl in the DESCRIPTION file. Do I need to modify the build script to get the master or dev version of curl from github with the install.packages call?

**Comment by krlmlr** [comment]
The install via `Remotes:` most likely won't work, because it's driven by devtools. Please install manually.
