### ISSUE TITLE
Unable to build simple package

### ISSUE THREAD

**Issue by Hong-Revo** [krlmlr/r-appveyor#77]
Hi, I'm testing out Appveyor integration on [a simple package](https://github.com/Hong-Revo/testPkg). The build is failing when it's trying to install devtools and its dependencies. It looks like compiling the needed packages from source isn't working. The log file is attached.

Since this is Windows, is it possible to use the package binaries instead?

[log.txt](https://github.com/krlmlr/r-appveyor/files/466940/log.txt)

**Comment by Hong-Revo** [comment]
Nevermind, forgot to set `USE_RTOOLS: true`.

Would still like to know if it's possible to install from binaries though. That would cut down on setup time sigificantly.

**Comment by krlmlr** [comment]
Usually, binary packages are installed if available; an essential file seems to be in bad shape on CRAN, should auto-fix (https://github.com/krlmlr/r-appveyor/issues/78#issuecomment-246343852).

**Comment by Hong-Revo** [comment]
Yep, seems to be working now. Thanks!
