### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by masalmon** [krlmlr/r-appveyor#78]
I see even this repo gets red flags on Appveyor-CI because of dependencies not being installed correctly "Packages required but not available: 'assertthat' 'Rcpp'", except on R-oldrel. Any idea what happened? If there is anywhere else where I should look for info I'd be happy to. :-)

**Comment by gaborcsardi** [comment]
It is a corrupt `PACKAGES` file on CRAN: https://cran.r-project.org/bin/windows/contrib/3.3/PACKAGES It is truncated. It will be fixed some time today, they claim.

**Comment by masalmon** [comment]
@gaborcsardi thanks a lot; in general where should I look for such info?

**Comment by gaborcsardi** [comment]
I don't know. I know about it because I noticed it myself, and digged up
what caused it.

**Comment by masalmon** [comment]
It works again now!
