### ISSUE TITLE
WARNINGS_ARE_ERRORS: 0 being ignored

### ISSUE THREAD

**Issue by iagomosqueira** [krlmlr/r-appveyor#79]
I have set

```
environment:

  global:
    WARNINGS_ARE_ERRORS: 0
```

but I am still getting

```
Found warnings, treated as errors.
+ echo 'Clear or unset the WARNINGS_ARE_ERRORS environment variable to ignore warnings.'
Clear or unset the WARNINGS_ARE_ERRORS environment variable to ignore warnings.
+ exit 1
Command exited with code 1
```

in

https://ci.appveyor.com/project/flr/flcore/build/job/v3f2y1jr1hduc4gy

Same thing if I simply delete the line. Anything I am doing wrong?

**Comment by krlmlr** [comment]
What happens with

```
  global:
    WARNINGS_ARE_ERRORS:
```

?

**Comment by iagomosqueira** [comment]
Yes, that worked

https://ci.appveyor.com/project/iagomosqueira/flcore/build/1.0.65

**Comment by iagomosqueira** [comment]
Should this be explained in README.md?

WARNINGS_ARE_ERRORS: Set to 1 to treat all warnings as errors, otherwise leave empty

**Comment by krlmlr** [comment]
Done.

**Comment by iagomosqueira** [comment]
Perfect. One last thing, should not having that line at all also work? It did not when I tried.

**Comment by iagomosqueira** [comment]
But it does in another project. Will investigate, thanks.
