### ISSUE TITLE
Corrupt R installer?

### ISSUE THREAD

**Issue by mattfidler** [krlmlr/r-appveyor#81]
Thank you for the awesome package.

I had an issue that just came up, I'm not sure if it is just me, but when searching it seems it has come up in the past.  Perhaps the R-3.3.2pached-win.exe has been deleted?

The code I'm getting is:
```
== 11/01/2016 20:56:39: Downloading R from: https://cloud.r-project.org/bin/windows/base/R-3.3.2patched-win.exe
== 11/01/2016 20:56:40: Running R installer
This command cannot be run due to the error: The file or directory is corrupted and unreadable.
7z a failure.zip *.Rcheck\*
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
```

For https://ci.appveyor.com/project/mattfidler/RxODE

**Comment by mattfidler** [comment]
See Issue #78

**Comment by krlmlr** [comment]
Could it be there's no "patched" version of R 3.3.2 because it's so brand new?

**Comment by gaborcsardi** [comment]
I think there is no R-patched binary available currently. Try using sg. else. There should always be an R-devel and an R-release binary.

**Comment by mattfidler** [comment]
Sorry I am new to this, can you point me to the documentation of sg else?

**Comment by gaborcsardi** [comment]
@mattfidler Set the `R_VERSION` environment variable to `stable`.

https://github.com/krlmlr/r-appveyor/blob/ad6a63596041ad4ebae7e46d1cd2df8f94ca4c88/README.md#environment-variables

Like in https://github.com/krlmlr/r-appveyor/blob/master/appveyor.yml#L20 but you'll only need a `matrix` and an `- R_VERSION` line.

**Comment by mattfidler** [comment]
Thanks it was me.  I appreciate your help.
