### ISSUE TITLE
Build vignettes not possible?

### ISSUE THREAD

**Issue by HenrikBengtsson** [krlmlr/r-appveyor#83]
What's the reason for skipping / erasing vignettes/ on MINGW and is there a way to avoid this?

```sh
    if [[ "${OS:0:5}" == "MINGW" ]]; then
        if [[ -d vignettes ]]; then
            rm -rf vignettes
            Rscript -e "d <- read.dcf('DESCRIPTION'); d[, colnames(d) == 'VignetteBuilder'] <- NA; write.dcf(d, 'DESCRIPTION')"
        fi
    fi
```

Source: https://github.com/krlmlr/r-appveyor/blob/master/r-travis/scripts/travis-tool.sh#L268-L273

I need my vignettes being built and installed in R.rsp, because they are used examples and package tests, which currently gives an error, cf. https://ci.appveyor.com/project/HenrikBengtsson/r-rsp/build/1.0.77/job/9ujx6vusum35jx2g

**Comment by krlmlr** [comment]
We currently have neither LaTeX nor pandoc on AppVeyor. Happy to review a PR that installs either or both.

**Comment by HenrikBengtsson** [comment]
I see. Though, my RSP vignettes can do without either of those.  I'll see if I can at least provide a PR making the above exclusion optional as a first step.

For LaTeX-based vignettes: It might be possible to install a fake `pdflatex` BAT script that tricks `R CMD build` and `R CMD check` by creating a fake PDF, e.g. `copy foo.tex foo.pdf` could be enough.  (I have an alternative of this internally of R.rsp. Unfortunately, not as a standalone script).

**Comment by IndrajeetPatil** [comment]
If I am not mistaken, building vignettes is still not supported on `r-appveyor`, correct?

**Comment by pat-s** [comment]
You need LaTeX and pandoc, both can be installed via workarounds. But its tedious to cache each of them and pandoc crashes from time to time. So its probably best to not do vignette checking on Appveyor.
