### ISSUE TITLE
remotes::install_github fails with build_vignettes argument

### ISSUE THREAD

**Issue by aappling-usgs** [krlmlr/r-appveyor#84]
We started having appveyor build problems right around two days ago, which is also right around when this commit went through: https://github.com/krlmlr/r-appveyor/commit/1e9add9a657ca181dbe4d28ea1e86b74f1391a6b

I think this line in particular is giving us trouble: https://github.com/krlmlr/r-appveyor/blob/4bb76b9fa783b3ee6c91b711a19fe423c5c9256a/r-travis/scripts/travis-tool.sh#L234. The change in the above commit was to switch from `devtools::install_github` to `remotes::install_github` :
```diff
-    Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="'"${CRAN}"'")); install_github(commandArgs(TRUE), build_vignettes = FALSE)' "$@"
+    Rscript -e 'options(repos=c(CRAN="'"${CRAN}"'")); remotes::install_github(commandArgs(TRUE), build_vignettes = FALSE)' "$@"
```

When dependencies need to be installed for a github package, an error and a warning now occur. E.g., for a GitHub package that requires the digest package:
```r
Installing 1 packages: digest
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (build_vignettes = FALSE)
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘digest’ failed
```

I have more success when I call remotes::install_github without the build_vignettes argument:
```r
Installing 1 packages: digest
package ‘digest’ successfully unpacked and MD5 sums checked
```

Is it an option to remove the `build_vignettes = FALSE` argument? As far as I can tell, `devtools` made use of the `build_vignettes` argument (https://github.com/hadley/devtools/blob/master/R/install.r#L66) but `remotes` doesn't (https://github.com/r-pkgs/remotes/blob/master/R/install.R#L2 and https://github.com/r-pkgs/remotes/search?utf8=%E2%9C%93&q=build_vignettes).

**Comment by krlmlr** [comment]
Thanks for the report and the detailed analysis. Let's hope packages with vignettes still can be installed, let me know if there are any problems.

**Comment by aappling-usgs** [comment]
Thanks for the fix (and in just 2 minutes, too!). My new build just finished and installed several packages from GitHub successfully, at least one of which has vignettes. As far as I can tell, we're good to go here.
