### ISSUE TITLE
3.4.0 R release pointer

### ISSUE THREAD

**Issue by LiNk-NY** [krlmlr/r-appveyor#86]
Hi Kirill, @krlmlr 

Is there a pointer to the alpha build of R version 3.4.0? 
I tried to use the version number `3.4.0` in the `key:value` pair but it directs to a broken link in the builder: 

https://cloud.r-project.org/bin/windows/base/old/3.4.0/R-3.4.0-win.exe

I'm trying to test a Bioconductor package that uses Bioconductor 3.5 with R version 3.4.0. 

BTW, this is the link to the alpha build:
https://cloud.r-project.org/bin/windows/base/rtest.html

Thank you. 

Regards,
Marcel

**Comment by krlmlr** [comment]
Have you tried `R_VERSION: devel`? r-appveyor currently doesn't support these alpha releases, looks like devel is the closest you can get to that.

**Comment by LiNk-NY** [comment]
Hi Kirill, @krlmlr 
Thanks for your prompt response. 
Unfortunately, `R_VERSION: devel` gives me R version `3.5.0`. 

Marcel

**Comment by krlmlr** [comment]
We could patch the PowerShell script to use a custom URL for the R download (e.g., from an environment variable). I'm happy to review a PR, but I won't have much time to do it myself.

Why is the version number so important for your tests? Ideally, R 3.5.0 should be basically the R 3.4.0 release candidate plus the changed version number.

**Comment by LiNk-NY** [comment]
That's reasonable. I will look into it but I don't guarantee a PR. 

As I noted earlier, Bioconductor `bioc-devel 3.5` uses R version `3.4.0`. 
The next devel version of Bioconductor will be using R `3.5.0` so this issue will be resolved over time. In the meantime, the builds using appveyor will be broken for any Bioconductor development package.

**Comment by LiNk-NY** [comment]
Actually, `bioc-devel 3.6` will be using R version `3.4.0`. The actual link for the `R.exe` is: 
https://cloud.r-project.org/bin/windows/base/R-3.4.0-win.exe
Could this be updated to reflect the new link? This is the most recent release of R.

**Comment by krlmlr** [comment]
I don't understand the question. What do you think should be updated?

**Comment by LiNk-NY** [comment]
When I use the R-release argument in the yml file, it tries to install `R 3.3.x`. R release is at `R 3.4.x`.

**Comment by krlmlr** [comment]
@gaborcsardi Does https://rversions.r-pkg.org/r-release-win need an update?

**Comment by krlmlr** [comment]
@gaborcsardi Are you still maintaining https://rversions.r-pkg.org/r-release-win?

**Comment by gaborcsardi** [comment]
Oh, yes, sorry, will do it today. In fact, I'll completely automate it today! Really!

**Comment by krlmlr** [comment]
No problem, thanks for supporting it!

**Comment by imanuelcostigan** [comment]
@krlmlr @gaborcsardi the release version of R is now 3.4.0 but both the r-pkg app and r-appveyor script still have this at 3.3.3. Do you know when this might be fixed? thanks

**Comment by imanuelcostigan** [comment]
to be fixed here: https://github.com/metacran/rversions.app/issues/3

**Comment by gaborcsardi** [comment]
Updated it, finally.

**Comment by krlmlr** [comment]
Thanks!
