### ISSUE TITLE
Version of remotes installed by r-appveyor fails with recursive soft dependencies

### ISSUE THREAD

**Issue by NikNakk** [krlmlr/r-appveyor#88]
Installing the current version of `dplyr` from github fails because of a recursive soft dependency on `dbplyr`. This is a problem in the version of `remotes` installed at present. The latest version on github has this fixed (https://github.com/r-pkgs/remotes/issues/31).

As a work-around, I've added `  - travis-tool.sh install_github r-pkgs/remotes` as the first line of my appveyor.yml, but ideally the appveyor script should be updated to use a later version of `remotes` by default.

**Comment by krlmlr** [comment]
@gaborcsardi: What are your release plans for the "remotes" package?

**Comment by gaborcsardi** [comment]
1-2 weeks, it soft-depends on `crancache`, which I need to finish first.

**Comment by krlmlr** [comment]
Thanks. @NikNakk: Happy to review a PR that installs from GitHub, we can merge and revert after "remotes" is on CRAN.

**Comment by gaborcsardi** [comment]
I think in general you are better off with the CRAN version, because `remotes` will change a lot soon. (After the next CRAN release.)

**Comment by krlmlr** [comment]
We could pin to a commit for now, by installing `r-pkgs/remotes@yxdas`.

**Comment by NikNakk** [comment]
One problem is that to install from github you need `remotes`. Would the plan to be to install the CRAN version and then use that to install the github version? The zip file from github can't be used directly because the package is in a subdirectory within the zip.

**Comment by krlmlr** [comment]
I'm fine with this workaround.

**Comment by hannesmuehleisen** [comment]
have same issue... e.g. https://ci.appveyor.com/project/hannesmuehleisen/MonetDBLite/build/job/m12mm3q2l6l8bv9k

**Comment by krlmlr** [comment]
Manually installing remotes from GitHub for now in dplyr et al.

**Comment by hannesmuehleisen** [comment]
yes, that works for me, too. thanks.

**Comment by krlmlr** [comment]
Is this still a problem?
