### ISSUE TITLE
update pandoc

### ISSUE THREAD

**Issue by gaborcsardi** [krlmlr/r-appveyor#89]
There are some self-contained binaries at 
https://files.r-hub.io/pandoc
in the `windows` directory.

**Comment by gaborcsardi** [comment]
These are 1.19.2.1, but they **do not** have the bug CRAN has been fighting with recently.

**Comment by krlmlr** [comment]
Thanks. Pandoc comes preinstalled on the AppVeyor images.

@FeodorFitsner: Any chance to deploy an update for pandoc? Thanks!

**Comment by FeodorFitsner** [comment]
@krlmlr I'm not sure we are explicitly installing pandoc to build worker images. Is it included in some other software?

**Comment by krlmlr** [comment]
I'll try to remember checking this the next time I'm debugging an AppVeyor build.
