### ISSUE TITLE
Command exited with code 5

### ISSUE THREAD

**Issue by gaborcsardi** [krlmlr/r-appveyor#90]
Anyone has seen this before? I have no clue why it is happening. E.g.
https://ci.appveyor.com/project/gaborcsardi/conf/build/1.0.5#L186

**Comment by krlmlr** [comment]
Do you need `GITHUB_PAT`?

**Comment by gaborcsardi** [comment]
Oh, sorry, probably.

**Comment by nhejazi** [comment]
Would it be possible to get a few details on how you resolved this issue?

I tried your proposed solution for my own package (adding a `GITHUB_PAT` with permission to access public repos), but this seems to now lead to `Error in readRDS(dest) : error reading from connection` in the installation for the same package. I cannot tell if this is related. Any help would be much appreciated.

**Comment by gaborcsardi** [comment]
I just added an encrypted GITHUB_PAT, based on the Appveyor web ui.

**Comment by nhejazi** [comment]
Got it. Thanks very much for the help @gaborcsardi.
