### ISSUE TITLE
appveyor r failures: Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by ajdamico** [krlmlr/r-appveyor#93]
hi, all of my R language cronjobs died this morning from the download failing at

    https://cloud.r-project.org/bin/windows/base/R-3.4.1patched-win.exe
   
error: "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
   
here's an example repo..  https://ci.appveyor.com/project/ajdamico/confidentiality/build/1.0.8

not sure if this is something that needs to be fixed in https://github.com/krlmlr/r-appveyor/blob/master/scripts/appveyor-tool.ps1 or just an internet hiccup that will pass on its own..  or if i'm being dumb in my appveyor.yml? thanks very much

**Comment by privefl** [comment]
Here, another example: https://ci.appveyor.com/project/privefl/bigstatsr/build/1.0.40

**Comment by krlmlr** [comment]
@FeodorFitsner: Is this SSL problem something we can/should solve on the client side? https://ci.appveyor.com/project/ajdamico/confidentiality/build/1.0.8#L18

**Comment by privefl** [comment]
This issue just disappeared for me: https://ci.appveyor.com/project/privefl/bigstatsr/build/1.0.41

**Comment by ajdamico** [comment]
me too..
