### ISSUE TITLE
Installed Rcpp version not supported by R-devel

### ISSUE THREAD

**Issue by Ewan-Keith** [krlmlr/r-appveyor#95]
One of my appveyor builds has recently started failing on R-devel, having previously ran fine on similar builds, but still runs successfully on R-release. The problem seems to be that appveyor is trying to install a version of Rcpp that is not consistent with R-devel. Output logs are below.

This is also suggested as the problem by the fact that I had the exact same problem for my travis linux builds (passing on release, failing on devel) but this was fixed when I cleared the travis package cache and rebuilt it from scratch. I don't think that appveyor uses package caching, but could be wrong.

The appveyor.yml is [here](https://github.com/Ewan-Keith/rstansim/blob/master/appveyor.yml) in case it's something in my setup that is prompting this.

```
// 00check.log
* using log directory 'C:/projects/rstansim/rstansim.Rcheck'
* using R Under development (unstable) (2017-09-16 r73293)
* using platform: i386-w64-mingw32 (32-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'rstansim/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'rstansim' version '0.1.1'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'rstansim' can be installed ... ERROR
Installation failed.
See 'C:/projects/rstansim/rstansim.Rcheck/00install.out' for details.
* DONE
Status: 1 ERROR
```

```
// 00install.out 
* installing *source* package 'rstansim' ...
** R
** preparing package for lazy loading
Error : package 'Rcpp' was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package 'rstansim'
* removing 'C:/projects/rstansim/rstansim.Rcheck/rstansim'
```

**Comment by krlmlr** [comment]
@eddelbuettel @kevinushey @jjallaire: Could you please comment on this?

**Comment by eddelbuettel** [comment]
See r-devel mailing list message by Luke Tierney.  ALTREP is in the r-devel master branch now _and requires all packages to be rebuilt against updated headers_ which is exactly what the error message says.

**Comment by krlmlr** [comment]
Thanks, Dirk.

To me this looks like we just need to wait until CRAN rebuilds their Windows packages, this shouldn't take more than a few days. Alternatively, `PKGTYPE=source` in `appveyor.yml` forces installation from source ([reference](https://github.com/krlmlr/r-appveyor/#environment-variables)).

**Comment by Ewan-Keith** [comment]
Yup, specifying `PKGTYPE=source` on R-devel does the trick for now. Will keep an eye on when the windows packages are rebuilt and will close the issue once that's the case.

Thanks to both.
