### ISSUE TITLE
Should NOT_CRAN=true be the default?

### ISSUE THREAD

**Issue by yutannihilation** [krlmlr/r-appveyor#97]
I saw some tests in my package skipped on AppVeyor.I suspect that this is because `NOT_CRAN=true` seems not set.

Travis CI does it here:
https://github.com/travis-ci/travis-build/blob/ddc0da6a1231e52708aa88fc71f557ea20cd3b99/lib/travis/build/script/r.rb#L53

(Sorry, I don't have time to confirm the assumption above now. Will check the other day.)

**Comment by krlmlr** [comment]
Thanks. I haven't thought about this, but you can always set the environment variable yourself in `appveyor.yml`. Need to rethink if this should be the default.

**Comment by yutannihilation** [comment]
Thanks! I will set it in my `appveyor.yml` for now :)

**Comment by krlmlr** [comment]
Keeping as is.
